start loading and splitting the data
start reading params file
start reading params file
something has happen wrong while getting data from data source
Traceback (most recent call last):
  File "src/split.py", line 22, in split_and_save
    random_state=params['base']['random_state']
KeyError: 'random_state'
something has happen wrong while getting data from data source
Traceback (most recent call last):
  File "src/split.py", line 22, in split_and_save
    random_state=params['base']['random_state']
KeyError: 'random_state'
start loading and splitting the data
start reading params file
start reading params file
Starting loading the data 
Starting loading the data 
Starting loading the data 
getting data from the data source
getting data from the data source
getting data from the data source
getting data from the data source
start reading params file
start reading params file
start reading params file
start reading params file
start reading params file
Data has been got sucuusfully
Data has been got sucuusfully
Data has been got sucuusfully
Data has been got sucuusfully
Data has been got sucuusfully
ending the loading the data
ending the loading the data
ending the loading the data
ending the loading the data
ending the loading the data
something has happen wrong while getting data from data source
Traceback (most recent call last):
  File "src/split.py", line 26, in split_and_save
    raw_dataset_path=params['load_path']['raw_dataset_csv']
KeyError: 'load_path'
something has happen wrong while getting data from data source
Traceback (most recent call last):
  File "src/split.py", line 26, in split_and_save
    raw_dataset_path=params['load_path']['raw_dataset_csv']
KeyError: 'load_path'
something has happen wrong while getting data from data source
Traceback (most recent call last):
  File "src/split.py", line 26, in split_and_save
    raw_dataset_path=params['load_path']['raw_dataset_csv']
KeyError: 'load_path'
something has happen wrong while getting data from data source
Traceback (most recent call last):
  File "src/split.py", line 26, in split_and_save
    raw_dataset_path=params['load_path']['raw_dataset_csv']
KeyError: 'load_path'
something has happen wrong while getting data from data source
Traceback (most recent call last):
  File "src/split.py", line 26, in split_and_save
    raw_dataset_path=params['load_path']['raw_dataset_csv']
KeyError: 'load_path'
start loading and splitting the data
start reading params file
start reading params file
Starting loading the data 
Starting loading the data 
Starting loading the data 
getting data from the data source
getting data from the data source
getting data from the data source
getting data from the data source
start reading params file
start reading params file
start reading params file
start reading params file
start reading params file
Data has been got sucuusfully
Data has been got sucuusfully
Data has been got sucuusfully
Data has been got sucuusfully
Data has been got sucuusfully
ending the loading the data
ending the loading the data
ending the loading the data
ending the loading the data
ending the loading the data
ending splitting the data 
ending splitting the data 
ending splitting the data 
ending splitting the data 
ending splitting the data 
